import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, FileCheck2, Leaf, ScanSearch, Settings2 } from "lucide-react";

import facilityImage from "@/assets/pvc-facility.jpg";
import flakesImage from "@/assets/pvc-flakes.jpg";
import { Button } from "@/components/ui/button";
import { Footer, Header, PageIntro, SectionHeading, FloatingWhatsApp } from "@/components/site";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About PolyCycle | Responsible PVC Recycling" },
  { name: "description", content: "Learn about a focused approach to collecting and processing PVC scrap into reusable recycled materials for B2B buyers." },
  { property: "og:title", content: "About PolyCycle | Responsible PVC Recycling" },
  { property: "og:description", content: "A quality-focused approach to PVC scrap recycling and industrial material supply." },
] }), component: AboutPage });

import { createFileRoute } from "@tanstack/react-router";

function AboutPage() {
  return <div><Header /><main><PageIntro eyebrow="About our company" title="Turning PVC scrap into reusable industrial materials." description="We recycle PVC scrap through organized processing operations to produce recycled PVC materials for industrial buyers." current="About" />
    <section className="section-space"><div className="container-shell grid items-center gap-12 lg:grid-cols-[0.95fr_1.05fr]"><div className="image-frame aspect-[1.1] overflow-hidden rounded-lg"><img src={facilityImage} alt="Clean PVC recycling facility with processing machinery" className="h-full w-full object-cover" width={1408} height={1008} loading="lazy" /></div><div><SectionHeading eyebrow="Our focus" title="Focused on responsible PVC recycling." description="Our business is focused on collecting and processing PVC scrap and converting it into reusable recycled material. The approach combines efficient processing, quality-focused operations, and professional B2B supply." /><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[Leaf, "Responsible recycling"], [Settings2, "Quality-focused processing"], [FileCheck2, "B2B supply"]].map(([Icon, label]) => <div key={label as string} className="border-t border-border pt-4"><Icon className="size-5 text-primary" /><p className="mt-4 text-sm font-bold leading-5">{label as string}</p></div>)}</div></div></div></section>
    <section className="section-space bg-secondary/45"><div className="container-shell"><SectionHeading eyebrow="Quality-focused processing" title="A practical review at each stage." description="The workflow is designed to keep material movement visible and create space for buyer requirements to be confirmed accurately." /><div className="mt-12 grid gap-5 md:grid-cols-4">{[[ScanSearch, "Incoming material inspection", "Review the material received before sorting begins."], [Settings2, "Material sorting", "Organize incoming material for the next processing stage."], [FileCheck2, "Processing control", "Keep the processing path aligned with the intended material form."], [Check, "Final material inspection", "Review the finished material before packaging and dispatch." ]].map(([Icon, title, text]) => <div key={title as string} className="border border-border bg-background p-6"><Icon className="size-6 text-primary" /><h3 className="mt-8 text-base font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text as string}</p></div>)}</div></div></section>
    <section className="section-space"><div className="container-shell grid items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="eyebrow text-primary">Material recovery</p><h2 className="display-title mt-4">Giving PVC scrap a new purpose.</h2><p className="body-copy mt-5">Recycling PVC can help recover useful material from waste streams and support more responsible material use. Our story is about the work of processing, reviewing, and preparing material for the next industrial use.</p><Button asChild className="mt-8"><Link to="/process">See the recycling process <ArrowRight /></Link></Button></div><div className="image-frame aspect-[1.08] overflow-hidden rounded-lg"><img src={flakesImage} alt="Close view of recycled PVC flakes and granules" className="h-full w-full object-cover" width={1200} height={912} loading="lazy" /></div></div></section>
    <section className="section-space bg-secondary/45"><div className="container-shell"><SectionHeading eyebrow="Certifications & compliance" title="Details available upon request." description="This section is intentionally structured for confirmed certificates and compliance documents when they are available. No certifications are claimed here." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["ISO", "Quality certifications", "Material compliance", "Other certifications"].map((item) => <div key={item} className="flex min-h-36 flex-col justify-between border border-dashed border-primary/30 bg-background p-6"><span className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Placeholder</span><div><h3 className="text-base font-bold">{item}</h3><p className="mt-2 text-xs text-muted-foreground">Certification details available upon request.</p></div></div>)}</div></div></section>
    <section className="section-space"><div className="container-shell"><div className="cta-panel"><div><p className="eyebrow text-accent">Keep exploring</p><h2 className="display-title mt-4 text-primary-foreground">See how the process moves from scrap to dispatch.</h2></div><Button asChild><Link to="/process">Explore our process <ArrowRight /></Link></Button></div></div></section>
  </main><Footer /><FloatingWhatsApp /></div>;
}